In [1]:
import platform
import datetime
import sys
import os


your_name, your_code, work_counter = "杜培博", 200507340136, 3
print(f'我是：{your_name}，学号：{your_code}，这是我的第 {work_counter} 次作业。')
print('现在是', datetime.datetime.now())
print('我的机器信息如下：')
print(platform.uname())

print('\n当前工作目录：')
print(os.getcwd())
print('\n当前目录的文件信息如下：')
print(os.listdir())
print('\n我安装包的情况:')
!pip list

我是：杜培博，学号：200507340136，这是我的第 3 次作业。
现在是 2021-09-19 13:27:17.532498
我的机器信息如下：
uname_result(system='Windows', node='LAPTOP-5PHEQ8I3', release='10', version='10.0.18362', machine='AMD64', processor='AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD')

当前工作目录：
E:\jupyter\curriculum_code\da_tow\week_03

当前目录的文件信息如下：
['.ipynb_checkpoints', '找出列表最多的那个数.ipynb']

我安装包的情况:
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0

You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


tabulate                           0.8.9
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            1.25.11
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wordcl

# 方案一：用原生的python

## 存入字典有两种方法

In [2]:
# 方法一
data = [1, 2, 3, 1, 3, 2, 1, 2, 2]
dic = {}
for i in data:
    if i in dic.keys():
        dic[i] += 1
    else:
        dic[i] = 1
print(dic)

{1: 3, 2: 4, 3: 2}


In [3]:
# 方法二 
data = [1, 2, 3, 1, 3, 2, 1, 2, 2]
dic = {}
for i in data:
    i = str(i)
    dic[i] = dic.get(i, 0) + 1
print(dic)

{'1': 3, '2': 4, '3': 2}


## 统计字典中的value次数

In [4]:
# argsort方法

import numpy as np
# 添加数据
lis = []
for i in dic:
    lis.append(dic[i])
    
tem = np.array(lis)
print("在列表中出现最多的那个数是：",list(dic.keys())[tem.argsort()[-1]])

在列表中出现最多的那个数是： 2


In [5]:
# argman方法

import numpy as np
# 添加数据
lis = []
for i in dic:
    lis.append(dic[i])
    
tem = np.array(lis)
print("在列表中出现最多的那个数是：",list(dic.keys())[tem.argmax()])

在列表中出现最多的那个数是： 2


In [6]:
# 打擂台法
lis = []
for i in dic:
    lis.append(dic[i])

diff = lis[0]
for i in lis:
    if i > diff:
        diff = i
        inde = lis.index(i)
print("在列表中出现最多的那个数是：", list(dic.keys())[inde])

在列表中出现最多的那个数是： 2


# 方案二：用from collections import Counter

In [7]:
import numpy as np
from collections import Counter

data = [1, 2, 3, 1, 3, 2, 1, 2, 2]
dic = Counter(data)

lis = []
for i in dic:
    lis.append(dic[i])

diff = lis[0]
for i in lis:
    if i > diff:
        diff = i
        inde = lis.index(i)
print("在列表中出现最多的那个数是：", list(dic.keys())[inde])

在列表中出现最多的那个数是： 2


# Numpy练习

## 数组切片

In [8]:
import numpy as np
 
# [start;stop;step]
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)
print(a[2:])

[2 4 6]
[2 4 6]
[2 3 4 5 6 7 8 9]


## 高级索引

### 获取元素

In [9]:
import numpy as np 
# 获取数组中(0,0)，(1,1)和(2,0)位置处的元素 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
print (x)
print (y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [10]:
# x[rows, cols] 行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]
import numpy as np

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('我们的数组是：')
print(x)
print('\n')
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print('这个数组的四个角元素是：')
print(y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


### 切片

In [11]:
# ...和：相同
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
d = a[...,1:]
print(d)

[[2 3]
 [5 6]
 [8 9]]


### 提取非空值

In [12]:
import numpy as np

a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


### 花式索引

In [13]:
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[[4,2,1,7]])  # [4,2,1,7]行
print (x[[-4,-2,-1,-7]])   #倒叙
print (x[np.ix_([1,5,7,2],[0,3,1,2])])  #[1,5,7,2]行,[0,3,1,2]元素

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### 广播机制

4x3 的二维数组与长为 3 的一维数组相加，等效于把数组 b 在二维上重复 4 次再运算：

In [14]:
import numpy as np 

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


### 遍历数组

In [15]:
import numpy as np 

# for x in np.nditer(a, order='F'):Fortran order，即是列序优先；
# for x in np.nditer(a.T, order='C'):C order，即是行序优先；

a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('以 C 风格顺序排序：')
for x in np.nditer(a, order =  'C'):  
    print (x, end=", " )
print ('\n')
print ('以 F 风格顺序排序：')
for x in np.nditer(a, order =  'F'):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


以 C 风格顺序排序：
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

以 F 风格顺序排序：
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

### 改变形状

In [16]:
a = np.arange(8)
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

numpy.ndarray.flat 是一个数组元素迭代器

In [17]:
import numpy as np
 
a = np.arange(9).reshape(3,3) 
print ('原始数组：')
for row in a:
    print (row)
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8


numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组

In [18]:
import numpy as np
#  order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。
a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
# 默认按行
 
print ('展开的数组：')
print (a.flatten())
print ('\n')
 
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以 F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


### numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组

In [19]:
import numpy as np
 
a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 ravel 函数之后：')
print (a.ravel())
print ('\n')
 
print ('以 F 风格顺序调用 ravel 函数之后：')
print (a.ravel(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[0 1 2 3 4 5 6 7]


以 F 风格顺序调用 ravel 函数之后：
[0 4 1 5 2 6 3 7]


### numpy.transpose 函数用于对换数组的维度/转置

In [20]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (np.transpose(a))

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 此外，输入数组的维度必须匹配否则将生成ValueError。

append 函数返回的始终是一个一维数组

In [21]:
import numpy as np
 
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')
 
print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### numpy.unique 函数用于去除数组中的重复元素

In [22]:
import numpy as np
 
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
 
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
 
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('\n')
 
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print ('\n')
 
print ('下标为：')
print (indices)
print ('\n')
 
print ('使用下标重构原数组：')
print (u[indices])
print ('\n')
 
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]


去重数组的下标：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]
